/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoFunctionsView: typeof import('./../src/components/views/AutoFunctionsView.vue')['default']
    Button: typeof import('./../src/components/ui/button/Button.vue')['default']
    Card: typeof import('./../src/components/ui/card/Card.vue')['default']
    CardAction: typeof import('./../src/components/ui/card/CardAction.vue')['default']
    CardContent: typeof import('./../src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./../src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./../src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./../src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./../src/components/ui/card/CardTitle.vue')['default']
    DashboardView: typeof import('./../src/components/views/DashboardView.vue')['default']
    Dialog: typeof import('./../src/components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./../src/components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./../src/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./../src/components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./../src/components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./../src/components/ui/dialog/DialogHeader.vue')['default']
    DialogOverlay: typeof import('./../src/components/ui/dialog/DialogOverlay.vue')['default']
    DialogScrollContent: typeof import('./../src/components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./../src/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./../src/components/ui/dialog/DialogTrigger.vue')['default']
    DropdownMenu: typeof import('./../src/components/ui/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./../src/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./../src/components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./../src/components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./../src/components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./../src/components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./../src/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./../src/components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./../src/components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./../src/components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./../src/components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./../src/components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./../src/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./../src/components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    GameConnectionView: typeof import('./../src/components/views/GameConnectionView.vue')['default']
    GameHelper: typeof import('./../src/components/GameHelper.vue')['default']
    GameHelperView: typeof import('./../src/components/views/GameHelperView.vue')['default']
    GamePathSettings: typeof import('./../src/components/settings/GamePathSettings.vue')['default']
    LoadingIcon: typeof import('./../src/components/ui/icons/LoadingIcon.vue')['default']
    MatchAnalysisView: typeof import('./../src/components/views/MatchAnalysisView.vue')['default']
    SafetyView: typeof import('./../src/components/views/SafetyView.vue')['default']
    Separator: typeof import('./../src/components/ui/separator/Separator.vue')['default']
    SettingsPanel: typeof import('./../src/components/settings/SettingsPanel.vue')['default']
    Sidebar: typeof import('./../src/components/ui/sidebar/Sidebar.vue')['default']
    Switch: typeof import('./../src/components/ui/switch/Switch.vue')['default']
    TauriDebugPanel: typeof import('./../src/components/debug/TauriDebugPanel.vue')['default']
    ThemeToggle: typeof import('./../src/components/ui/theme-toggle/ThemeToggle.vue')['default']
  }
}
