// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 建议视角
 */
export type AdvicePerspective = "SelfImprovement" | "Targeting" | "Collaboration";
