// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 建议分类
 */
export type AdviceCategory = "Laning" | "Farming" | "Teamfight" | "Vision" | "Positioning" | "Decision" | "Champion";
