pub mod analysis_data;
pub mod auth;
pub mod champ_select;
pub mod connection;
pub mod ddragon;
pub mod gameflow;
pub mod liveclient;
pub mod lobby;
pub mod matches;
pub mod matchmaking;
pub mod opgg;
pub mod perks;
pub mod ranked;
pub mod request;
pub mod summoner;
pub mod types;
pub mod unified_polling;
pub mod optimized_polling;
pub mod ws;

// Re-export 常用的类型和函数，便于外部使用
pub use connection::service::ConnectionManager;
